'use client'

import jsPDF from 'jspdf'
import type { Invoice } from '@/lib/data-store'

export async function generateInvoicePDF(invoice: Invoice) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let yPosition = 10

  
  // Set fonts
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(24)
  doc.setTextColor(255, 140, 66) // Orange color
  doc.text(invoice.businessName, pageWidth / 2, yPosition, { align: 'center' })

  yPosition += 8
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text('Professional Retail Management System - Bricto', pageWidth / 2, yPosition, { align: 'center' })

  yPosition += 10
  doc.setDrawColor(255, 140, 66)
  doc.line(10, yPosition, pageWidth - 10, yPosition)

  yPosition += 6
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('INVOICE', 10, yPosition)

  yPosition += 12
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)

  // Invoice Details
  const leftCol = 10
  const rightCol = pageWidth / 2 + 5

  doc.text(`Invoice #: ${invoice.id}`, leftCol, yPosition)
  doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString('en-IN')}`, rightCol, yPosition)

  yPosition += 7
  doc.text(`Customer: ${invoice.customerName}`, leftCol, yPosition)
  doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString('en-IN')}`, rightCol, yPosition)

  yPosition += 12

  // Table Headers
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(10)
  doc.setFillColor(255, 140, 66)
  doc.setTextColor(255, 255, 255)

  const colWidths = [60, 20, 35, 35]
  const headers = ['Product', 'Qty', 'Price (₹)', 'Amount (₹)']

  let xPos = leftCol
  headers.forEach((header, i) => {
    doc.rect(xPos, yPosition - 5, colWidths[i], 7, 'F')
    doc.text(header, xPos + 2, yPosition, { align: 'left' })
    xPos += colWidths[i]
  })

  yPosition += 10
  doc.setFont('Helvetica', 'normal')
  doc.setTextColor(0, 0, 0)

  // Table Rows
  invoice.items.forEach((item) => {
    const itemTotal = item.salePrice * item.quantity
    const row = [
      item.productName,
      item.quantity.toString(),
      `₹${item.salePrice.toFixed(2)}`,
      `₹${itemTotal.toFixed(2)}`,
    ]

    xPos = leftCol
    row.forEach((cell, i) => {
      doc.text(cell, xPos + 2, yPosition, { align: i > 0 ? 'right' : 'left' })
      xPos += colWidths[i]
    })

    yPosition += 6
  })

  // Totals Section
  yPosition += 5
  doc.setDrawColor(200, 200, 200)
  doc.line(10, yPosition, pageWidth - 10, yPosition)

  yPosition += 6
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(10)

  const totalsX = pageWidth - 60
  doc.text('Subtotal:', totalsX, yPosition)
  doc.text(`₹${invoice.subtotal.toFixed(2)}`, pageWidth - 10, yPosition, { align: 'right' })

  yPosition += 6
  const taxPercent = invoice.subtotal > 0 ? ((invoice.taxAmount / invoice.subtotal) * 100).toFixed(1) : '0'
  doc.text(`Tax (${taxPercent}%):`, totalsX, yPosition)
  doc.text(`₹${invoice.taxAmount.toFixed(2)}`, pageWidth - 10, yPosition, { align: 'right' })

  yPosition += 8
  doc.setFont('Helvetica', 'bold')
  doc.setFontSize(12)
  doc.setDrawColor(255, 140, 66)
  doc.line(totalsX - 5, yPosition - 2, pageWidth - 10, yPosition - 2)
  doc.text('Total Amount:', totalsX, yPosition)
  doc.setTextColor(255, 140, 66)
  doc.text(`₹${invoice.total.toFixed(2)}`, pageWidth - 10, yPosition, { align: 'right' })

  // Footer
  yPosition = pageHeight - 15
  doc.setFont('Helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Bricto - Professional Retail Management System', pageWidth / 2, yPosition, { align: 'center' })

  yPosition += 5
  doc.text('Thank you for your business!', pageWidth / 2, yPosition, { align: 'center' })

  // Save PDF
  doc.save(`Invoice-${invoice.id}.pdf`)
}
